### ISSUE TITLE
New Task: classfying questions

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#17]
1. women's equality compared to man in public sphere (men vs. women in public sphere - traditional male role): ex) political leadership question when job is scarce
2. men's equality compared to women in private sphere (men vs. women in private sphere, traditional female role): ex) men stay at home
3. women's balancing in public and private (balance of traditional gender role), leaving men: ex) should women work when they have child, housewife work?  
4. male dominance, sexual harassment, etc.

**Comment by lallemang** [comment]
This comment goes through the survey items @byngdeuk and I classified differently:


**Line 23: Question: Husbands should have final say in all decisions concerning the family.**
Byung-Deuk left this one blank and I categorized it as 4 because I think this question taps into male dominance over women.

**Lines 28-30: Question: Women and men should have equal rights in making the decision to divorce.**
Byung-Deuk left these blank and I categorized them as 4 because I think they tap into male dominance over women.

**Line 60-62: Question: A woman should devote almost all her time to her family.**
Byung-Deuk categorized these as 3 and I categorized them as 2 because the question doesn't mention any aspect of the women's life outside of the home - hence, I didn't think it was tapping into women's _balancing_ of public/private life.

**Line 77: Question: Men should take as much responsibility as women for the home and children.**
Byung-Deuk categorized this as 3 and I categorized it as 2 for the same reason above. The question doesn't compare home life to public life, so I don't think it is a question about balancing the two.

**Line 94: Question: A woman and her family will all be happier if she goes out to work.**
Byung-Deuk categorized this as 1 and I categorized it as 3 because the question is tapping into the woman's need/desire to balance home life (i.e. her family and making them happy) and public life (i.e. going out to work).

**Line 106: Question: Do you agree or disagree with this statement? Women should take care of running their homes and leave running the country up to men.**
This one stumped me, so I simply wanted to point it out. I think there is a reasonable argument for categorizing it as 3 or 2. The question references both the private and the public sector, which would lean more toward 3. But it's also basically a "women belong at home" question, which we've been categorizing as 2. I'm fine with either coding decision, but I think we should give it some thought.

**Line 107: Question: A husband's job is to earn money; A wife's job is to look after the home and family.**
Byung-Deuk categorized this as 1, but I have the same thought as above. I think this question should be a 2 or a 3, and whatever category we decide is best for the previous question is the category I think we should give this one.

**Line 108: Question: The best thing for a woman to do is to take care of the house.**
Byung-Deuk categorized this as 3 and I categorized it as 2 because the question is not asking about women balancing home life and public life.

**Line 110-118: Question: Being a housewife is just as fulfilling as working for pay.**
Byung-Deuk categorized these questions as 2 and I categorized them as 3 because the question is directly comparing home life to public life.

**Line 130-131: Question: In your opinion, how important are each of the following traits in a woman? Independence.**
Byung-Deuk categorized these questions as 1 and I categorized them as 4 because I think the opposite of "independence" for women is male dominance, and "independence" isn't solely part of public or private/domestic life.

**Line 136-138: Question: It is acceptable in Islam for male and female university students to attend classes together?**
Byung-Deuk categorized these questions as 4 and I categorized them as 1 because I think this is tapping more into whether women belong in the public sphere than whether men have the right to dominate women. To me, this question is similar to questions about women being allowed in political leadership or in the working world, which we've been categorizing as 1.

**Line 170: Question: If there is a limited number of jobs, do you approve or disapprove of a married woman holding a job in business or industry when her husband is able to support her?**
Byung-Deuk categorized this as 1 and I categorized it as 3 because the question is comparing the woman's role/duty as a wife to her ability to work, inquiring what the respondent thinks the proper balance should be between these things.

**Line 172: Question: View on connection between women's happiness and marriage: A woman's happiness lies in a marriage.**
Byung-Deuk categorized this as 1 and I categorized it as 2 because I think marriage falls more into the private/domestic/home life that we are specifying with category 2. I think an implication of this question is that "a woman's happiness lies in her traditional domestic roles as a wife/mother, not out in the public working world."

**Line 173: Question: Muslim women should have the same rights as Muslim men to marry non-Muslims.**
Byung-Deuk categorized this as 1 and I categorized it as 2 for the same reason above. I think marriage questions are tapping more into private/domestic life than the public working world.

**Line 174: Question: The woman has the right to marry a man of her choice.**
Byung-Deuk categorized this as 1 and I categorized it as 2 for the same reason above.

**Line 175-176: Question: Working women should receive paid maternity leave when they have a baby.**
This question also stumped me. I could see it reasonably falling into category 1 or 3, so I'd appreciate more discussion about it. On the one hand, the question is referring to both the woman's public life (i.e. working for pay) and her private life (i.e. having a baby to take care of), which would lean toward category 3. On the other hand, the crux of the question is whether she deserves to be paid by her job, which falls more under category 1.

**Line 180-182: Question: A man can be responsible for looking after the home and children just as well while the woman works full-time.**
Byung-Deuk categorized these questions as 2 and I categorized them as 3 because I think the question is asking about the proper balance between home and work life for both men and women.

**Line 183-185: Question: Please tell me if you completely agree with it, mostly agree with it, mostly disagree with it or completely disagree with it: A wife must always obey her husband.**
Byung-Deuk categorized this as 2 and I categorized it as 4 because I think this question is directly referring to male dominance over women.

**Line 234: Question: A women’s primary role is in the home.**
Byung-Deuk categorized this as 3 and I categorized it as 2 because the question is not comparing women's home life to their potential public life. It is only focused on the woman's domestic role.

**Line 239: Question: Even if both parents work, it is still better if the mother has main responsibility for looking after the home and children.**
Byung-Deuk categorized this as 1 and I categorized it as 3 because it is asking about the mother's responsibility to balance her home and work life.

**Line 241-243: If a woman wants to have a child as a single parent but she doesn't want to have a stable relationship with a man, do you approve or disapprove?**
Byung-Deuk categorized these as 3 and I categorized them as 2 because these questions are solely focused on the woman's personal, private obligations and relationships. The question is not referring to these private aspects of her life _relative_ to her public life.

**Line 244: Question: View on wife working: If a husband has sufficient income it is better for his wife not to have a job.**
Byung-Deuk categorized this as 1 and I categorized it as 3 because I think the question is asking about the proper balance between financial need pushing women into the working world and women's duty to stay home if at all possible.

**Line 247: Question: A toddler really needs a full-time mother.**
Byung-Deuk categorized this as 3 and I categorized it as 2 because the question is only referring to women's private lives as mothers. It is not asking about that responsibility relative to women's public lives. 

**Line 248-266: Question: It is much better for everyone involved if the man is the achiever outside the home and the woman takes care of the home and family.**
These questions also stumped me, and I wanted to point them out. Similar to my discussion of Line 106, I could see these questions being categorized as 2 or 3. I'm not sure if this question is asking about a balance between private and public life (i.e. category 3) or if it's really more of a "women belong at home" question (i.e. category 2).

**Line 276: Question: A woman can travel abroad by herself if she wishes.**
Byung-Deuk categorized this as 1 and I categorized this as 4 because I think the reasonable implication of "by herself" is "without a male chaperone", which falls more in line with male dominance over women.

**Line 277: Question: On this list are various groups of people, could you please sort out any that you would not like to have as neighbours? Unmarried mothers.**
Byung-Deuk categorized this as 3 and I categorized it as 2 because I think neighbors also fall under the umbrella of home/domestic life.

**Comment by byngdeuk** [comment]
I agreed with the much of Lindsey's classification. Below Items are the things we need to discuss.

**Line 106: Question: Do you agree or disagree with this statement? Women should take care of running their homes and leave running the country up to men.**

**Line 175-176: Question: Working women should receive paid maternity leave when they have a baby.**

**Line 248-266: Question: It is much better for everyone involved if the man is the achiever outside the home and the woman takes care of the home and family.**

**Comment by byngdeuk** [comment]
In addition, I fill up the missing explanation about below items in the following link: https://github.com/fsolt/dcpo_gender_roles/blob/master/data-raw/egr_questions.csv

nsss_combo | jobpref5 | affactw2 | c(5:1) | Women should be given preferential treatment when applying for jobs and promotions | 1 Strongly Agree / 5 Strongly Disagree

amb_combo | jobs7 | gen1 | c(7:1) | Changing the subject again, some say that when there is not enough work, men should have a greater right to jobs than women. | 1 Strongly Agree / 7 Strongly Disagree

amb_us2012 | jobs7 | gen1 | c(7:1) | Changing the subject again, some say that when there is not enough work, men should have a greater right to jobs than women.

This is the line 164-166 in the following link: https://github.com/fsolt/dcpo_gender_roles/blob/master/data-raw/surveys_egr_classification.csv.

I guess we agree to give those three questions classified as "1". 
Please let me know if we didn't!

**Comment by byngdeuk** [comment]
I re-classify the questions and the below are the questions that my and Lindsey's classifications (I guess Lindsey's the classification is before the last meeting) differ.
I think it is great to see those questions together.

pewrel2015_ee | bearchild4 | q16d | c(1:4) | 1 | 2
usgss | biochild4 | fekids1 | c(1:4) | 1 | 2
lb2006 | chrespon3 | p88n | c(1,3,2) | 1 | 2
allbus | equalroles4 | fr08 | c(4:1) | 1 | 2
nsss_combo | family5a | wdevfam | c(1:5) | 3 | 2
allbus | fatherwork4a | fr11 | c(1:4) | 2 | 3
usgss | godchild4 | fekids5 | c(1:4) | 1 | 2
usgss | homecountry2 | fehome | c(1:2) | 1 | 2
issp2002 | house5a | v12 | c(5:1) | 1 | 2
cdcee | household4 | v232 | c(1:4) | 1 | 2
wvs_combo | independence5 | d072 | c(5:1) | 1 | 4
arabb2 | inheritance4 | q60109 | c(4:1) | 4 | 1
usgss | limjob2 | feworkif | c(2:1) | 1 | 3
jgss | marrihap4 | q4wnmga | c(1:4) | 1 | 2
tcmeg2004 | marrynon5 | m710n | c(5:1) | 1 | 2
tcmeg2004 | marryright5 | m710s | c(5:1) | 1 | 2
allbus | msww4 | fr12 | c(4:1) | 2 | 3
tcmeg2004 | permitsec5 | m710x | c(5:1) | 4 | 2
usgss | relation2 | tradmod | c(1:2) | 1 | 2
ases2000 | rolehome4 | v0215 | c(1:4) | 1 | 2
allbus | secondshift4 | fr10 | c(1:4) | 1 | 3
evs_combo | sparent3 | d023 | c(0,2,1) | 3 | 2
jgss | suffjob4 | q4wwjbia | c(1:4) | 1 | 3
jgss | surname4 | op4name | c(1:4) | 4 | 2
nsss1989 | todller5 | todndmo | c(1:5) | 3 | 2
usgss | tradroles4 | fefam | c(1:4) | 2 | 3
evs_combo | unmarried2 | a124_40 | c(1:0) | 4 | 2
evs_combo | wantch4 | d062 | c(1:4) | 1 | 3
nsss1989 | wifejob5 | wkpfnowh | c(5:1) | 1 | 3

**Comment by lallemang** [comment]
Hi @fsolt and @byngdeuk! 

I finished re-classifying the survey items, and I updated the spreadsheet accordingly. I've once again listed below which survey items Byung-Deuk and I have coded differently (or questions that I think are worthy of further discussion). 

**Line 3: Question: Women have a responsibility to society to bear children.**
Byung-Deuk: 1
Lindsey: 3
_No mention or implication of men in this question. Equality is achieved by allowing women to embrace responsibilities other than bearing children (i.e. allowing them to perform duties in both the public and private sphere)._

**Line 7: Question: Women are biologically better-suited to care for children. How important do you think this reason is for explaining why women are more likely to take care of children?**
Byung-Deuk: 1
Lindsey: 2
_This is tough because the wording of this question isn’t really getting at opinions on gender roles – it’s asking about the role of biology in constructing gender roles. However, I think equality is achieved in this framework by acknowledging that men are just as capable as women at taking care of children, implying they can/should share this responsibility in their private lives._

**Line 15: Question: Men ought to do a larger share of childcare than they do now.**
Byung-Deuk: 3
Lindsey: 2
_The egalitarian response to this question is to agree, meaning that equality is achieved in the home in this question. I also thought that we discussed category-3 questions being questions where there is no mention or implication of men. They are questions comparing women’s public and private lives, not relative to men’s._

**Line 21-22: Question: Housework and childcare should be the responsibility of the mother or the father or be shared equally by both?**
Byung-Deuk: 1
Lindsey: 2
_Equality is achieved in the household by both men and women sharing the responsibility of childcare equally._

**Line 44-45: Question: In your opinion, how important are each of the following traits in a woman? Being educated.**
Byung-Deuk: 1
Lindsey: 3
_I think these questions, especially when taken together, are asking the respondent to prioritize which elements of women’s public and private lives are most important for evaluating their quality as women – tapping into women’s balancing of these characteristics._

**Line 56: Question: The best way to organise family and work life is for both partners to work full-time and to look after the home and children equally.**
Byung-Deuk: 1
Lindsey: 2
_I coded this as a 2 not because I think it is more of a 2 than a 1, but because I think it could be coded as either, and I’m not sure how we should handle that._

**Line 75: Question: Family life often suffers because men concentrate too much on their work.**
Byung-Deuk: 3
Lindsey: 2
_Equality is achieved by men spending more time at home, with the implication being that women and men should both hold responsibility for “family life”. Also, if we end up agreeing that this should be a 2, we may want to rename this item. There are currently two items named “familywork5b”. The other item corresponds to this question: “A woman and her family will all be happier if she goes out to work,” which I agree with Byung-Deuk in coding as a category-3 question. But it probably doesn’t make sense for two questions that we’re calling the same item to actually fall into two different categories._

**Line 83: Question: It is God's will that women care for children. How important do you think this reason is for explaining why women are more likely to take care of children?**
Byung-Deuk: 1
Lindsey: 2
_Echoing my thoughts from Line 7, this one is tough because this question is asking for the respondent’s opinion on what determines gender roles, not on the gender roles themselves. However, like I said for the question in Line 7, I think equality is achieved here by acknowledging that men are equally capable of taking care of children, implying they can/should share this responsibility in their private lives._

**Line 84-85: Question: In your opinion, how important are each of the following traits in a woman? Being a good mother.**
Byung-Deuk: 1
Lindsey: 3
_Same as my comments from Line 44-45. I think these questions, especially when taken together, are asking the respondent to prioritize which elements of women’s public and private lives are most important for evaluating their quality as women – tapping into women’s balancing of these characteristics._ 

**Line 86-87: Question: Question: In your opinion, how important are each of the following traits in a woman? Being a good wife.**
Byung-Deuk: 1
Lindsey: 3
_Same as my comments above. I think these questions, especially when taken together, are asking the respondent to prioritize which elements of women’s public and private lives are most important for evaluating their quality as women – tapping into women’s balancing of these characteristics._

**Line 95-96: Question: In your opinion, how important are each of the following traits in a woman? Having work outside home.**
Byung-Deuk: 1
Lindsey: 3
_Same as my comments above. I think these questions, especially when taken together, are asking the respondent to prioritize which elements of women’s public and private lives are most important for evaluating their quality as women – tapping into women’s balancing of these characteristics._

**Line 107: Question: A husband's job is to earn money; a wife's job is to look after the home and family.**
Byung-Deuk: 1
Lindsey: 2
_I coded this as a 2 not because I think it’s more of a 2 than a 1, but because I think it could be coded as either, and I’m not sure how to handle that._

**Line 130-131: Question: In your opinion, how important are each of the following traits in a woman? Independence.**
Byung-Deuk: 1
Lindsey: 3
_Same as my comments for the other questions from this series. I think these questions, especially when taken together, are asking the respondent to prioritize which elements of women’s public and private lives are most important for evaluating their quality as women – tapping into women’s balancing of these characteristics._

**Line 150-158: Question: Having a job is the best way for a woman to be an independent person.**
Byung-Deuk: 1
Lindsey: 3
_This question isn’t comparing women’s rights to employment to men’s, but rather comparing parts of women’s lives where they can obtain independence – meaning, this question is asking about how women balance the different aspects of their lives._

**Line 172: Question: View on Connection between Women Happiness and Marriage. A woman's happiness lies in a marriage.**
Byung-Deuk: 1
Lindsey: 3
_Similar to the questions asking the respondent to identify what the most important characteristics of women are, I think this question is comparing the public and private aspects of women’s lives. The implication of this question is something along the lines of “Does a woman’s happiness lie in marriage or in her work (or in something else less traditional than marriage)?”_

**Line 177-179: Question: If the woman earns more than the man, she will almost certainly have problems.**
Byung-Deuk: 1
Lindsey: 3
_I think the focus of this question is that working women will have private, relational issues at home if they make more than their husbands. So, it’s less about women having the right to make more than men, and more about balancing their public achievements with the private ramifications of those achievements._

**Line 231: Question: Which type of relationship would you prefer? 1 A relationship where the man has the main responsibility for providing the household income and the woman has the main responsibility for taking care of the home and family / 2 A relationship where the man and woman equally share responsibility for providing the household income and taking care of the home and family.**
Byung-Deuk: 1
Lindsey: 2
_I coded this as a 2 not because I think it’s more of a 2 than a 1, but because I think it could be coded as either, and I’m not sure how to handle that._

**Line 234: Question: A women’s primary role is in the home.**
Byung-Deuk: 1
Lindsey: 3
_I think this question is comparing the public/private aspects of women’s lives, not comparing women’s rights to public life relative to men’s._

**Line 239: Question: Even if both parents work, it is still better if the mother has main responsibility for looking after the home and children.**
Byung-Deuk: 1
Lindsey: 3
_The focus of this question is women’s responsibility to balance work life and taking care of the home and children._

**Line 248-266: Question: It is much better for everyone involved if the man is the achiever outside the home and the woman takes care of the home and family.**
Byung-Deuk: 2
Lindsey: 1
_I coded this as a 1 not because I think it’s more of a 1 than a 2, but because I think it could be coded as either, and I’m not sure how to handle that._

**Line 277: Question: On this list are various groups of people. Could you please sort out any that you would not like to have as neighbours? Unmarried mothers.**
Byung-Deuk: 4
Lindsey: ?
_I don’t know what to think about this question, so I’d like to talk more about it._

**Line 280-287: Question: A job is alright but what most women really want is a home and children.**
Byung-Deuk: 1
Lindsey: 3
_This isn’t comparing women’s right to employment to men’s, but rather comparing which aspects of women’s lives they care about more – public or private._

**Line 291: Question: What kind of marriage do you think is the more satisfying way of life, number 1 or number 2? (SHOW CARD) 1 One where the husband provides for the family and the wife takes care of the house and children / 2 One where the husband and wife both have jobs and both take care of the house and children.**
Byung-Deuk: 1
Lindsey: 2
_I coded this as a 2 not because I think it’s more of a 2 than a 1, but because I think it could be coded as either, and I’m not sure how to handle that._
