### ISSUE TITLE
Writings

### ISSUE THREAD

**Issue by byngdeuk** [fsolt/dcpo_gender_roles#18]
Hi Lindsey!

I try to write up four dimension things and re-write the introduction section.
I updated my changes on the github "dcpo_gender_role.rmd" file.
Could you review the intro and my write up and let me know how do you think about it?
I as foreigner am not good at writing paper as fast as you can 🙂.
Please correct any sentence that looks ugly!

All My Best,
-Byung-Deuk.

**Comment by byngdeuk** [comment]
"Gender Attitudes in Africa: Liberal Egalitarianism Across 34 Countries" in _Social Forces_

**Comment by byngdeuk** [comment]
Flows of paper

measurements of the four categories: real questionnaires classified into the four categories (two or four representative questionnaires) and repeatition of the reasoning my we focus on public sector (education, work, and politics) ->> Then, we just dive into our data (from sources to estimates including cross-section estimates) + polarization measures + plot some time-series (may be all countries or some countries) ->> Concluding remarks + how to use our data,

**Comment by fsolt** [comment]
Current word count, per https://leeper.shinyapps.io/pdfcount/ is 4,038(!), so a tiny bit of slimming to do . . .

**Comment by fsolt** [comment]
I propose cutting the entire second-to-last paragraph.  Okay, I'll just do it.

**Comment by fsolt** [comment]
Okay, I shifted a bit to the previous paragraph and cut the rest.  That takes it to 3950.  Seriously, I didn't think we were that close to the word count limit.  

Anyway, please be sure to give it a close read and edit this week, @byngdeuk and @lallemang.

**Comment by byngdeuk** [comment]
I will closely read it and edit it this week!

**Comment by byngdeuk** [comment]
Before our meeting today, I want to share my opinion on the draft.

First, I think this paper is really well organized with the problem of the sparse survey data, the introduction of DCPO packages, method, PGE data, validation, information about how to access our data, caveat for using PGE with uncertainty.

Thus, there is no big edit on this draft.

There are two things I have though.

**1. In Page 3: "Which countries are the most data-rich?"  – I think we can cut it off.**
-> Reason: The paragraph starting with the above question can be understood without the above question.


**2. In Page 11: "Busemeyer, Marius R, Aurélien Abrassart and Roula Nezi. 2019. “Beyond Positive and Negative: New Perspectives on Feedback Effects in Public Opinion on the Welfare State.” British Journal of Political Science. 1-26."**
-> Reason: In the current draft, the above citation is written as "Busemeyer, Marius R, Aurélien Abrassart and Roula Nezi. 2021. “Beyond Positive and Negative: New Perspectives on Feedback Effects in Public Opinion on the Welfare State.” British Journal
of Political Science ." 
 However, the above article was published in 2019 rather than 2021 as below.
![image](https://user-images.githubusercontent.com/46687506/103559889-80dfe480-4e7c-11eb-9be0-6eadae075837.png)

**Comment by lallemang** [comment]
Hi Fred and Byung-Deuk,

I have also read through the current draft of the paper and don't see much need for major edits. My more specific comments are listed by section below.

**Abstract:** Clear and fits the word limit. Emphasizes why it is important to have comparable, rich data on public opinion toward gender roles and concisely describes how the PGE dataset addresses this need.

**Examining the Source Data:** Also clear and concise. Is it intentional to emphasize SO much that the available public opinion data is very sparse? Is this a good thing to emphasize because DCPO addresses this issue? Just checking, because this emphasis is very clear in this section of the paper.

**Estimating PGE:** Oh just kidding, you answer my question in the first paragraph of this section - So that's good! :) But perhaps it's worth clarifying in the preceding section that yes, sparsity and incomparability are problems, but they are problems that we address. This could just be a minor tweak in some of the wording. Additionally, the gray whiskers on the plots in Figure 2 are difficult to see. I know we're tight on space, so maybe we can't really do anything about that. But I'll throw it out there in case it's worth editing.

**Validating PGE:** Clear and concise explanations of convergent and construct validation. The plots are pretty and helpful! :)

**Using the PGE Dataset:** In an ideal world with a larger word limit, I'd say it might be helpful to add a sentence or two explaining what it means to 'consider the uncertainty' of the PGE estimates. This section clearly emphasizes that failing to do so can lead to wrong conclusions and that there are packages available to help the researcher 'consider the uncertainty.' But it's not very clear what that actually means, methodologically speaking. Maybe that doesn't matter for this type of paper though, since we're mainly focused on just introducing the dataset.

Overall, I think the paper is in great shape! It's easy to follow and well written. I don't see any major issues that need editing.

Talk to you both soon! :)
